version: 2

updates:

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      alpinejs:
        patterns:
          - "alpinejs"
          - "@types/alpinejs"
    ignore:
      - dependency-name: "astro"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@astrojs/*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(deps)"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(actions)"
